<a href="https://colab.research.google.com/github/baortraam/Machine-learning-projects/blob/master/college_admission_pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Step 1: Import the dependencies**

In [33]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

**Step 2: Data preprocessing**

Upload data

In [6]:
df = pd.read_csv('/content/genz_college_admission_prediction.csv', encoding = 'latin-1')
df

,student_id,age,gender,state,family_income,high_school_gpa,sat_score,act_score,attendance_rate,ap_courses,extracurricular_count,volunteer_hours,leadership_positions,coding_projects,social_media_hours,online_certifications,essay_score,recommendation_score,interview_score,admission_status
0,1,22,Male,Ohio,32560,3.20,734,27,91.0,3,3,85,1,4,4.8,1,96.3,90.5,71.7,1
1,2,19,Male,Virginia,39084,4.00,988,26,100.0,0,5,103,1,4,2.7,2,59.9,55.2,93.0,1
2,3,20,Male,Ohio,21615,2.90,1600,28,97.7,2,3,78,2,1,5.4,4,75.2,70.3,70.0,1
3,4,22,Male,Illinois,109493,3.86,1302,28,91.6,4,3,98,0,2,1.8,2,80.7,81.9,98.7,1
4,5,18,Male,Florida,50314,2.50,1342,30,91.8,3,4,35,1,2,5.8,3,63.1,73.7,67.5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999996,20,Female,New York,127978,3.98,984,27,94.9,3,6,24,1,2,3.9,2,72.6,76.0,82.0,1
999996,999997,16,Male,Ohio,47661,3.49,940,25,80.6,2,4,206,1,3,6.7,0,88.5,72.9,67.4,1
999997,999998,21,Female,Washington,88044,2.77,1103,16,95.9,0,1,67,0,2,3.7,3,73.1,85.9,77.6,1
999998,999999,17,Female,Virginia,55654,3.71,1208,27,87.8,3,8,24,1,2,2.8,0,72.6,60.9,71.0,1
999999,1000000,18,Male,California,59923,3.41,1241,28,94.0,2,4,184,1,1,1.8,3,70.3,91.7,55.3,1

In [7]:
df.describe()

,student_id,age,family_income,high_school_gpa,sat_score,act_score,attendance_rate,ap_courses,extracurricular_count,volunteer_hours,leadership_positions,coding_projects,social_media_hours,online_certifications,essay_score,recommendation_score,interview_score,admission_status
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,500000.500000,19.000294,71701.069023,3.188329,1099.198467,23.468139,91.748151,2.999739,3.999927,99.452955,1.201223,1.999254,4.506180,1.997953,74.912247,77.954531,72.775141,0.881292
std,288675.278933,1.999321,47253.555181,0.476299,217.409113,5.908590,5.526156,1.729285,2.001495,50.019098,1.095605,1.414804,1.790163,1.414445,11.805257,9.873768,14.522840,0.323445
min,1.000000,16.000000,2124.000000,0.870000,400.000000,1.000000,63.200000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,17.600000,28.800000,0.500000,0.000000
25%,250000.750000,17.000000,39953.000000,2.860000,952.000000,19.000000,88.000000,2.000000,3.000000,63.000000,0.000000,1.000000,3.300000,1.000000,66.900000,71.300000,62.800000,1.000000
50%,500000.500000,19.000000,59877.000000,3.200000,1100.000000,24.000000,92.000000,3.000000,4.000000,91.000000,1.000000,2.000000,4.500000,2.000000,75.000000,78.000000,73.000000,1.000000
75%,750000.250000,21.000000,89688.000000,3.540000,1248.000000,28.000000,96.000000,4.000000,5.000000,127.000000,2.000000,3.000000,5.700000,3.000000,83.100000,84.700000,83.100000,1.000000
max,1000000.000000,22.000000,977775.000000,4.000000,1600.000000,36.000000,100.000000,12.000000,15.000000,517.000000,8.000000,11.000000,12.900000,12.000000,100.000000,100.000000,100.000000,1.000000

Drop irrelevant features

In [8]:
df =  df.drop(columns = ['student_id', 'age',	'gender',	'state'])
df

,family_income,high_school_gpa,sat_score,act_score,attendance_rate,ap_courses,extracurricular_count,volunteer_hours,leadership_positions,coding_projects,social_media_hours,online_certifications,essay_score,recommendation_score,interview_score,admission_status
0,32560,3.20,734,27,91.0,3,3,85,1,4,4.8,1,96.3,90.5,71.7,1
1,39084,4.00,988,26,100.0,0,5,103,1,4,2.7,2,59.9,55.2,93.0,1
2,21615,2.90,1600,28,97.7,2,3,78,2,1,5.4,4,75.2,70.3,70.0,1
3,109493,3.86,1302,28,91.6,4,3,98,0,2,1.8,2,80.7,81.9,98.7,1
4,50314,2.50,1342,30,91.8,3,4,35,1,2,5.8,3,63.1,73.7,67.5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,127978,3.98,984,27,94.9,3,6,24,1,2,3.9,2,72.6,76.0,82.0,1
999996,47661,3.49,940,25,80.6,2,4,206,1,3,6.7,0,88.5,72.9,67.4,1
999997,88044,2.77,1103,16,95.9,0,1,67,0,2,3.7,3,73.1,85.9,77.6,1
999998,55654,3.71,1208,27,87.8,3,8,24,1,2,2.8,0,72.6,60.9,71.0,1
999999,59923,3.41,1241,28,94.0,2,4,184,1,1,1.8,3,70.3,91.7,55.3,1

Split data into X, y

In [13]:
X = df.iloc[:, 0:15]

In [14]:
y = df.iloc[:, 15]

Scale X

In [15]:
scaler = StandardScaler()

In [18]:
X = scaler.fit_transform(X)
X

array([[-0.8283205 ,  0.02450365, -1.67977618, ...,  1.81171525,
         1.27058644, -0.07403104],
       [-0.69025675,  1.70412308, -0.5114713 , ..., -1.27165842,
        -2.3045449 ,  1.39262494],
       [-1.0599434 , -0.60535363,  2.3034995 , ...,  0.02437502,
        -0.77523943, -0.1910881 ],
       ...,
       [ 0.34585629, -0.87829179,  0.01748563, ..., -0.15351193,
         0.8047053 ,  0.33222578],
       [-0.33959513,  1.09526104,  0.50044631, ..., -0.19586596,
        -1.72725741, -0.12223101],
       [-0.24925267,  0.46540375,  0.65223395, ..., -0.39069452,
         1.39212065, -1.2032873 ]])

Splitting the dataset into training and testing sets

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 11,
                                                          test_size = 0.2,
                                                          stratify = y)

**Step 3: Training model**

In [36]:
model = LogisticRegression(class_weight = 'balanced',
                           random_state = 42)

In [37]:
model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', random_state=42)

In [38]:
y_pred = model.predict(X_test)

In [39]:
model.score(X_test, y_test)

0.785825

In [40]:
model.score(X_train, y_train)

0.78824

**Step 4: Model evaluation**

In [41]:
print(confusion_matrix(y_test, y_pred))

[[ 19153   4589]
 [ 38246 138012]]

In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.33      0.81      0.47     23742
           1       0.97      0.78      0.87    176258

    accuracy                           0.79    200000
   macro avg       0.65      0.79      0.67    200000
weighted avg       0.89      0.79      0.82    200000

**Step 5: Make a predictive system**

In [ ]:
input_data = ()

input_data_to_numpy_array = np.asarray(input_data)

input_data_reshaped = input_data_to_numpy_array.reshape(1,-1)

y_predict = model.predict(input_data_reshaped)

if (y_predict[0]=='1'):
  print('Accepted')
else:
  print('Rejected')

Example:

In [43]:
input_data = (109493,3.86,1302,28,91.6,4,3,98,0,2,1.8,2,80.7,81.9,98.7)

input_data_to_numpy_array = np.asarray(input_data)

input_data_reshaped = input_data_to_numpy_array.reshape(1,-1)

y_predict = model.predict(input_data_reshaped)

if (y_predict[0]=='1'):
  print('Accepted')
else:
  print('Rejected')

Rejected