<a href="https://colab.research.google.com/github/baortraam/Machine-learning-projects/blob/master/Student_lifestyle_and_stress.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Step 1: Import the dependencies**

In [21]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

**Step 2: Data preprocessing**

In [2]:
df = pd.read_csv('/content/student-lifestyle-and-stress-dataset.csv', encoding = 'latin-1')
df

,Student_Type,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
0,school,6.868702,1.711722,3.176942,NaN,8.0,7.0,2.0,1
1,school,8.519088,3.251084,3.880787,93.978465,6.0,4.0,3.0,1
2,college,4.498770,6.306885,2.936172,64.421253,7.0,1.0,12.0,1
3,school,8.591223,2.384922,5.222832,81.868960,2.0,7.0,7.0,0
4,college,5.329293,9.345179,7.815869,85.847982,5.0,6.0,10.0,1
...,...,...,...,...,...,...,...,...,...
25495,college,7.803069,7.328193,2.018277,75.435607,5.0,1.0,12.0,0
25496,school,6.734607,2.680109,3.355559,63.387386,8.0,9.0,2.0,1
25497,college,7.701671,2.631250,2.948252,79.818930,4.0,3.0,4.0,1
25498,school,5.903426,3.450424,6.823894,96.680773,2.0,6.0,6.0,0
25499,college,7.419726,6.442748,3.356066,81.452460,9.0,5.0,6.0,1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25500 entries, 0 to 25499
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_Type        24248 non-null  object
 1   Sleep_Hours         24167 non-null  float64
 2   Study_Hours         24223 non-null  float64
 3   Social_Media_Hours  24188 non-null  float64
 4   Attendance          24195 non-null  float64
 5   Exam_Pressure       24230 non-null  float64
 6   Family_Support      24209 non-null  float64
 7   Month               24186 non-null  float64
 8   Stress_Level        25500 non-null  int64
dtypes: float64(7), int64(1), object(1)
memory usage: 1.8+ MB

In [3]:
df.describe()

,Sleep_Hours,Study_Hours,Social_Media_Hours,Attendance,Exam_Pressure,Family_Support,Month,Stress_Level
count,24167.000000,24223.000000,24188.000000,24195.000000,24230.000000,24209.000000,24186.000000,25500.000000
mean,6.458948,4.696477,3.555614,81.270961,5.369748,5.798298,6.500992,0.299882
std,1.504228,2.240148,1.901528,12.052045,2.394003,2.232371,3.455308,0.458215
min,2.008586,-1.433434,0.000040,-5.000000,1.000000,1.000000,1.000000,0.000000
25%,5.438360,3.078230,2.152249,73.738894,4.000000,4.000000,3.000000,0.000000
50%,6.542566,4.538138,3.500709,81.942959,5.000000,6.000000,6.000000,0.000000
75%,7.531571,6.135670,4.864312,90.106859,7.000000,7.000000,10.000000,1.000000
max,9.997527,22.444460,9.962134,120.000000,10.000000,10.000000,12.000000,1.000000

In [24]:
df['Stress_Level'].value_counts()

Stress_Level
0    17853
1     7647
Name: count, dtype: int64

In [8]:
X = df.iloc[:, 0:8]

In [9]:
y = df.iloc[:, 8]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y, random_state = 11)

In [10]:
cat_cols = ['Student_Type']

In [11]:
num_cols = ['Study_Hours', 'Social_Media_Hours', 'Attendance', 'Exam_Pressure', 'Family_Support', 'Month']

In [34]:
cat_pipeline = Pipeline(steps = [
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('one-hot-encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=True))
])

In [35]:
num_pipeline = Pipeline(steps = [
    ('impute', SimpleImputer(strategy='mean')),
    ('scale', StandardScaler())
])

In [36]:
col_transformer = ColumnTransformer(transformers = [
    ('cat_pipeline', cat_pipeline, cat_cols),
    ('num_pipeline', num_pipeline, num_cols)],
    remainder = 'drop',
    n_jobs = -1)

**Step 3: Training model**

In [37]:
model = RandomForestClassifier(class_weight='balanced',
                               random_state=42,
                               n_jobs=-1,
                               n_estimators=200,
                               max_depth=15,
                               min_samples_split=10,
                               max_features='sqrt')

In [38]:
pipefinal = make_pipeline(col_transformer, model)

In [39]:
pipefinal.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(n_jobs=-1,
                                   transformers=[('cat_pipeline',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('one-hot-encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Student_Type']),
                                                 ('num_pipeline',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer()),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['Study_Hours',
                                                   'Social_Media_Hours',
                                                   'Attendance',
                                                   'Exam_Pressure',
                                                   'Family_Support',
                                                   'Month'])])),
                ('randomforestclassifier',
                 RandomForestClassifier(class_weight='balanced', max_depth=15,
                                        min_samples_split=10, n_estimators=200,
                                        n_jobs=-1, random_state=42))])

In [41]:
pipefinal.score(X_test, y_test)

0.8074509803921569

In [42]:
pipefinal.score(X_train, y_train)

0.9115686274509804

In [43]:
y_pred = pipefinal.predict(X_test)

**Step 4: Model evaluation**

In [44]:
print(confusion_matrix(y_pred, y_test))

[[3050  461]
 [ 521 1068]]

In [45]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.85      0.87      0.86      3511
           1       0.70      0.67      0.69      1589

    accuracy                           0.81      5100
   macro avg       0.78      0.77      0.77      5100
weighted avg       0.81      0.81      0.81      5100